[package]
name = "arkdata"
version = "2.0.0"
authors = ["astral4 <88992929+astral4@users.noreply.github.com>"]
edition = "2021"
readme = "README.md"
homepage = "https://github.com/astral4/arkdata"
repository = "https://github.com/astral4/arkdata"
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
again = { version = "0.1.2", default-features = false, features = ["rand"] }
ahash = { version = "0.8.7", features = ["serde"] }
anyhow = "1.0.79"
bytes = "1.5.0"
futures = "0.3.30"
glob = "0.3.1"
image = { version = "0.24.7", default-features = false, features = ["png"] }
once_cell = "1.19.0"
pyo3 = { version = "0.20.2", default-features = false, features = ["auto-initialize"] }
rayon = "1.8.0"
reqwest = { version = "0.11.23", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.195", features = ["derive", "rc"] }
serde_json = "1.0.111"
tap = "1.0.1"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
toml = "0.8.8"
zip = "0.6.6"

[dev-dependencies]
uuid = { version = "1.6.1", default-features = false, features = ["v4"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
