[package]
name = "arkdata"
version = "2.0.0"
authors = ["astral4 <88992929+astral4@users.noreply.github.com>"]
edition = "2021"
readme = "README.md"
homepage = "https://github.com/astral4/arkdata"
repository = "https://github.com/astral4/arkdata"
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
again = { version = "0.1.2", default-features = false, features = ["rand"] }
ahash = { version = "0.8.3", features = ["serde"] }
anyhow = "1.0.71"
bytes = "1.4.0"
flume = "0.10.14"
futures = "0.3.28"
glob = "0.3.1"
image = { version = "0.24.6", default-features = false, features = ["png"] }
once_cell = "1.18.0"
pyo3 = { version = "0.19.1", default-features = false, features = ["auto-initialize"] }
rayon = "1.7.0"
reqwest = { version = "0.11.18", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.166", features = ["derive", "rc"] }
serde_json = "1.0.100"
tap = "1.0.1"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros"] }
toml = "0.7.6"
zip = "0.6.6"

[dev-dependencies]
uuid = { version = "1.4.0", default-features = false, features = ["v4"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
