[package]
name = "arkdata"
version = "0.1.0"
authors = ["astral4 <88992929+astral4@users.noreply.github.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
ahash = { version = "0.8.2", features = ["serde"] }
anyhow = "1.0.67"
async-trait = "0.1.60"
config = { version = "0.13.3", default-features = false, features = ["toml"]}
futures = "0.3.25"
once_cell = "1.17.0"
reqwest = "0.11.13"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["rt-multi-thread", "macros"]}
zip = "0.6.3"

[dev-dependencies]
uuid = { version = "1.2.2", default-features = false, features = ["v4"]}

[profile.release]
strip = true
lto = true
codegen-units = 1
