[package]
name = "arkdata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.89"
anyhow = "1.0.67"
reqwest = "0.11.13"
ahash = { version = "0.8.2", features = ["serde"] }
futures = "0.3.25"
zip = "0.6.3"

[dependencies.tokio]
version = "1.23.0"
features = ["rt-multi-thread", "fs", "macros"]

[dev-dependencies]

[dev-dependencies.uuid]
version = "1.2.2"
default-features = false
features = ["v4"]

[profile.release]
strip = true
lto = true
codegen-units = 1
