[fetch-settings]
server = "US"
details_path = "details.json"
hashes_path = "hashes.json"
force_fetch = false
path_start_patterns = ["gamedata/", "arts/charavatars/", "arts/misc/"]
output_dir = "assets"
update_cache = true

[unpack-settings]
input_dir = "assets"
output_dir = "results"