name: Fetch and convert assets

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Build Rust program
      run: cargo build --release

    - name: Fetch assets
      run: ./target/release/arkdata

    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "poetry"

    - name: Set up Python environment
      run: |
        poetry env use 3.11
        poetry install

    - name: Unpack assets
      run: poetry run python main.py
    
    - name: Commit updates
      run: |
        git config --global user.name "Kawabot"
        git config --global user.email "actions@users.noreply.github.com"
        git pull --all
        git add results/assets/torappu/dynamicassets/arts/skills
        git commit -m "Update assets"
        git push